$host.ui.RawUI.WindowTitle = $MyInvocation.MyCommand.Name
$exclude = @(
    "atxHandler\tvalidating nipost"
    "atxHandler\tnew atx"
    "atxHandler\tatx failed contextual validation"
    "bootstrap\t"
    "beacon\t"
    "blockHandler\tnew block"
    "blockGenerator\tno consensus on mesh hash. NOT doing optimistic filtering"
    "blockGenerator\tno feasible txs for block"
    "blockCert\tgenerating certificate"
    "conState\treceived mempool txs"
    "executor\texecuted block"
    "executor\toptimistically executed block"
    "grpc\t"
    "grpc.Node\tGRPC NodeService.Status"
    "hare\tstatus round completed"
    "hare\tcommit round completed"
    "hare\tconsensus process started"
    "hare\tpreround ended"
    "hare\thare terminated with success"
    "hare\tconsensus process terminated"
    "hare\tnot voting on proposal from malicious identity"
    "hare\tencountered late preround message"
    "hare\tinvalid certificate"
    "hare\tlate message failed contextual validation"
    "hare\tmessage failed syntactic validation"
    "hare\tearly message failed syntactic validation, discarding"
    "mesh\talready synced certificate"
    "hare\tcounting votes from malicious identities in aggregated messages"
    "hareOracle\t"
    "mesh\tconsensus results"
    "malfeasance\tnew malfeasance proof"
    "nipostValidator\tVerifying with PoW creator ID"
    "nipostValidator\tverifying POST with pow creator ID"
    "post\tinitialization: file already initialized"
    "post\tfound unrecognized file"
    "proposalListener\tnew ballot"
    "proposalListener\tnew proposal"
    "proposalBuilder\tminer has no valid vrf nonce, not building proposal"
    "sync\tnode is too far behind"
    "sync\tbegin fork finding with peer"
    "sync\tfound hash fork with peer"
    "sync\tmesh hash synced data from peer"
    "sync\tadopted cert from peer"
    "\tstarting post proof verifier worker"
    "trtl\tencoded votes"
    "timesync\tfailed to read response from peer"
    "trtl\tcandidate layer is verified"
)
Get-Content log_XXXX.txt -Tail 30000 -Wait | Select-String ($exclude -Join '|') -NotMatch
Pause
